package fi.pelam.javafxutil

import org.junit.Assert._
import org.junit.Test

case class TestImmutable(a: Int, b: Int) {
}

class ScalaToJavafxPropsTest {
  val immutable = TestImmutable(1, 2)
  val scalaToJavafxProps = ScalaToJavafxProps.forClass[TestImmutable]
  val props: JavafxProps[TestImmutable] = scalaToJavafxProps(immutable)

  @Test
  def testPropertyNames(): Unit = {
    assertEquals("a, b", props.propertyNames.reduce(_ + ", " + _))
  }

  @Test
  def testIntegerPropertyValue(): Unit = {
    assertEquals(1, props.getNumberProperty("a").getValue.intValue())
  }

  @Test
  def testToString(): Unit = {
    assertEquals("JavafxProps for TestImmutable(1,2) (generated by JavaFxPropsMaker)", props.toString)
  }

}